default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  database: <%= ENV.fetch('POSTGRES_DB') %>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: crimethinc_development

test:
  <<: *default
  database: crimethinc_test

production:
  <<: *default
  database: crimethinc_production
  username: crimethinc
  password: <%= ENV['CRIMETHINC_DATABASE_PASSWORD'] %>
